CREATE TABLE IF NOT EXISTS characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  species TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_name ON characters (name);
CREATE INDEX IF NOT EXISTS idx_species ON characters (species);

INSERT INTO characters (name, species) VALUES
('Stan Smith', 'Human'),
('Roger Smith', 'Alien'),
('Francine Smith', 'Human'),
('Steve Smith', 'Human'),
('Hayley Smith', 'Human'),
('Klaus', 'Goldfish'),
('Avery Bullock', 'Human'),
('Jeff Fischer', 'Human'),
('Principal Lewis', 'Human'),
('Snot Lonstein', 'Human'),
('Barry Robinson', 'Human'),
('Toshi Yoshida', 'Human'),
('Akiko Yoshida', 'Human'),
('Debbie Hyman', 'Human'),
('Greg Corbin', 'Human'),
('Terry Bates', 'Human'),
('Dick Reynolds', 'Human'),
('Agent Duper', 'Human'),
('Reginald', 'Koala'),
('Betty Smith', 'Human'),
('Jack Smith', 'Human'),
('Rusty Smith', 'Human'),
('Bob Memari', 'Human'),
('Linda Memari', 'Human'),
('Lisa Silver', 'Human'),
('Father Donovan', 'Human'),
('Rogu', 'Alien'),
('Al Tuttle', 'Human'),
('Barb Hanson', 'Human'),
('Captain Monty', 'Human'),
('Sharri Rothberg', 'Human'),
('Buckle', 'Human'),
('Sergei Kruglov', 'Human'),
('Hideki Yoshida', 'Human'),
('Hiko Yoshida', 'Human'),
('Esther Lonstein', 'Human'),
('Danuta Tenuta', 'Human'),
('Nerfer', 'Human'),
('Santa Claus', 'Human'),
('Dr. Kalgary', 'Human'),
('James A. Garfield', 'Human (Clone)'),
('Emperor Zing', 'Alien'),
('Foster', 'Alien'),
('Stelio Kontos', 'Human'),
('Krampus', 'Demon'),
('Chuck White', 'Human'),
('Betsy White', 'Human'),
('Christie White', 'Human'),
('Bah Bah Ling', 'Human'),
('Mah Mah Ling', 'Human'),
('Gwen Ling', 'Human'),
('Nicholas Dawson', 'Human'),
('Cassandra Dawson', 'Human'),
('Janet Dawson', 'Human'),
('Liberty Belle Corbin-Bates', 'Human'),
('Ricky Spanish', 'Alien'),
('Jeannie Gold', 'Alien'),
('The Legman', 'Alien'),
('Dr. Penguin', 'Alien'),
('Tearjerker', 'Alien'),
('Kevin Bacon', 'Alien'),
('Pete Pendelman', 'Alien'),
('Sweeps McCullough', 'Alien'),
('Mr. Stan-Dan Deliver', 'Alien'),
('Ruby Zeldastein', 'Alien'),
('Julia Rogerts', 'Alien'),
('Bing Cooper', 'Alien'),
('Ace Chapman', 'Alien'),
('The Tender Vigilante', 'Alien'),
('Bob Danelou', 'Alien'),
('Martin Sugar', 'Alien'),
('Ragi-Baba', 'Alien'),
('Genevieve Vavance', 'Alien'),
('Jenny Fromdabloc', 'Alien'),
('Sidney Huffman', 'Alien'),
('Laura Vanderbooben', 'Alien'),
('Chex LeMeneux', 'Alien'),
('Buck Wetnap', 'Alien'),
('Billy Jesusworth', 'Alien'),
('Ace Crouton', 'Alien');